### ISSUE TITLE
Add Oracle BookToken/USD to get fixed USD rates as an option.

### ISSUE THREAD

**Issue by davidp94** [davidp94/open-decentralized-gds#8]
https://github.com/davidp94/open-decentralized-gds/blob/3864ab98866cd3e5ccb662a9c0f579cc848fd713/contracts/Flights/RevenueManagementSystem.sol#L36

**Comment by countzen2000** [comment]
I don't know if I approve of this. ;)

**Comment by davidp94** [comment]
Decided to use stablecoin.
